/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsIsland: typeof import('./src/components/Island/AnalyticsIsland.vue')['default']
    ChatIsland: typeof import('./src/components/Island/ChatIsland.vue')['default']
    Confetti: typeof import('./src/components/zxcomponent/Confetti/Confetti.vue')['default']
    DashboardIsland: typeof import('./src/components/Island/DashboardIsland.vue')['default']
    DatabaseIsland: typeof import('./src/components/Island/DatabaseIsland.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FileEditorModal: typeof import('./src/components/FileEditorModal/index.vue')['default']
    FilesIsland: typeof import('./src/components/Island/FilesIsland.vue')['default']
    FriendCard: typeof import('./src/components/zxcomponent/FriendCard/FriendCard.vue')['default']
    FriendDetailInfo: typeof import('./src/components/manage/FriendDetailInfo.vue')['default']
    FriendTrendChart: typeof import('./src/components/manage/FriendTrendChart.vue')['default']
    GroupCard: typeof import('./src/components/zxcomponent/GroupCard/GroupCard.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeSidebar: typeof import('./src/components/home/HomeSidebar.vue')['default']
    Island: typeof import('./src/components/Island/Island.vue')['default']
    LocationAddress: typeof import('./src/components/zxcomponent/LocationAddress/LocationAddress.vue')['default']
    LogIsland: typeof import('./src/components/Island/LogIsland.vue')['default']
    ManageIsland: typeof import('./src/components/Island/ManageIsland.vue')['default']
    MemberCard: typeof import('./src/components/zxcomponent/MemberCard/MemberCard.vue')['default']
    MessageBox: typeof import('./src/components/zxcomponent/MessageBox/MessageBox.vue')['default']
    Notification: typeof import('./src/components/zxcomponent/Notification/Notification.vue')['default']
    PluginCard: typeof import('./src/components/zxcomponent/PluginCard/PluginCard.vue')['default']
    PluginConfigModal: typeof import('./src/components/zxcomponent/PluginConfigModal/PluginConfigModal.vue')['default']
    PluginIsland: typeof import('./src/components/Island/PluginIsland.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreCard: typeof import('./src/components/zxcomponent/StoreCard/StoreCard.vue')['default']
    StoreIsland: typeof import('./src/components/Island/StoreIsland.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
    WhiteScreen: typeof import('./src/components/zxcomponent/WhiteScreen/WhiteScreen.vue')['default']
    ZXInput: typeof import('./src/components/zxcomponent/ZXInput.vue')['default']
    ZXMonacoEditor: typeof import('./src/components/ZXMonacoEditor/index.vue')['default']
  }
}
