/* QQ 默认表情（小表情，多为 APNG 动画）—— 源 koishijs/QFace (MIT) assets/qq_emoji 全量。
   CDN 直链优先（有动画取 apng，否则静态 png），加载失败回退后端本地路由
   /zhenxun/api/v1/sticker/qq/{id}.png（同样 apng 优先）。*/
import type { StickerItem, StickerPack } from "./stickers";

const CDN_BASE =
    "https://cdn.jsdelivr.net/gh/koishijs/QFace@master/public/assets/qq_emoji";
const LOCAL_ROUTE = "/zhenxun/api/v1/sticker/qq";

const cdn = (id: string, kind: "apng" | "png") => `${CDN_BASE}/${id}/${kind}/${id}.png`;
const localPng = (id: string) => `${LOCAL_ROUTE}/${id}.png`;

/** 由 QQ CDN 地址推导后端本地兜底；非 QQ 表情返回 null */
export function qqntLocalFallback(url: string): string | null {
    const m = url.match(/\/qq_emoji\/([^/]+)\/(?:apng|png)\//);
    return m ? localPng(m[1]) : null;
}

export const QQ_DEFAULT_STICKERS: StickerItem[] = [
    { id: "qq-0", faceId: "0", name: "惊讶", description: "惊讶", path: cdn("0", "apng"), fallback: localPng("0"), type: "image", tags: ["QQ", "惊讶"] },
    { id: "qq-1", faceId: "1", name: "撇嘴", description: "撇嘴", path: cdn("1", "apng"), fallback: localPng("1"), type: "image", tags: ["QQ", "撇嘴"] },
    { id: "qq-2", faceId: "2", name: "色", description: "色", path: cdn("2", "apng"), fallback: localPng("2"), type: "image", tags: ["QQ", "色"] },
    { id: "qq-3", faceId: "3", name: "发呆", description: "发呆", path: cdn("3", "apng"), fallback: localPng("3"), type: "image", tags: ["QQ", "发呆"] },
    { id: "qq-4", faceId: "4", name: "得意", description: "得意", path: cdn("4", "apng"), fallback: localPng("4"), type: "image", tags: ["QQ", "得意"] },
    { id: "qq-5", faceId: "5", name: "流泪", description: "流泪", path: cdn("5", "apng"), fallback: localPng("5"), type: "image", tags: ["QQ", "流泪"] },
    { id: "qq-6", faceId: "6", name: "害羞", description: "害羞", path: cdn("6", "apng"), fallback: localPng("6"), type: "image", tags: ["QQ", "害羞"] },
    { id: "qq-7", faceId: "7", name: "闭嘴", description: "闭嘴", path: cdn("7", "apng"), fallback: localPng("7"), type: "image", tags: ["QQ", "闭嘴"] },
    { id: "qq-8", faceId: "8", name: "睡", description: "睡", path: cdn("8", "apng"), fallback: localPng("8"), type: "image", tags: ["QQ", "睡"] },
    { id: "qq-9", faceId: "9", name: "大哭", description: "大哭", path: cdn("9", "apng"), fallback: localPng("9"), type: "image", tags: ["QQ", "大哭"] },
    { id: "qq-10", faceId: "10", name: "尴尬", description: "尴尬", path: cdn("10", "apng"), fallback: localPng("10"), type: "image", tags: ["QQ", "尴尬"] },
    { id: "qq-11", faceId: "11", name: "发怒", description: "发怒", path: cdn("11", "apng"), fallback: localPng("11"), type: "image", tags: ["QQ", "发怒"] },
    { id: "qq-12", faceId: "12", name: "调皮", description: "调皮", path: cdn("12", "apng"), fallback: localPng("12"), type: "image", tags: ["QQ", "调皮"] },
    { id: "qq-13", faceId: "13", name: "呲牙", description: "呲牙", path: cdn("13", "apng"), fallback: localPng("13"), type: "image", tags: ["QQ", "呲牙"] },
    { id: "qq-14", faceId: "14", name: "微笑", description: "微笑", path: cdn("14", "apng"), fallback: localPng("14"), type: "image", tags: ["QQ", "微笑"] },
    { id: "qq-15", faceId: "15", name: "难过", description: "难过", path: cdn("15", "apng"), fallback: localPng("15"), type: "image", tags: ["QQ", "难过"] },
    { id: "qq-16", faceId: "16", name: "酷", description: "酷", path: cdn("16", "apng"), fallback: localPng("16"), type: "image", tags: ["QQ", "酷"] },
    { id: "qq-18", faceId: "18", name: "抓狂", description: "抓狂", path: cdn("18", "apng"), fallback: localPng("18"), type: "image", tags: ["QQ", "抓狂"] },
    { id: "qq-19", faceId: "19", name: "吐", description: "吐", path: cdn("19", "apng"), fallback: localPng("19"), type: "image", tags: ["QQ", "吐"] },
    { id: "qq-20", faceId: "20", name: "偷笑", description: "偷笑", path: cdn("20", "apng"), fallback: localPng("20"), type: "image", tags: ["QQ", "偷笑"] },
    { id: "qq-21", faceId: "21", name: "可爱", description: "可爱", path: cdn("21", "apng"), fallback: localPng("21"), type: "image", tags: ["QQ", "可爱"] },
    { id: "qq-22", faceId: "22", name: "白眼", description: "白眼", path: cdn("22", "apng"), fallback: localPng("22"), type: "image", tags: ["QQ", "白眼"] },
    { id: "qq-23", faceId: "23", name: "傲慢", description: "傲慢", path: cdn("23", "apng"), fallback: localPng("23"), type: "image", tags: ["QQ", "傲慢"] },
    { id: "qq-24", faceId: "24", name: "饥饿", description: "饥饿", path: cdn("24", "apng"), fallback: localPng("24"), type: "image", tags: ["QQ", "饥饿"] },
    { id: "qq-25", faceId: "25", name: "困", description: "困", path: cdn("25", "apng"), fallback: localPng("25"), type: "image", tags: ["QQ", "困"] },
    { id: "qq-26", faceId: "26", name: "惊恐", description: "惊恐", path: cdn("26", "apng"), fallback: localPng("26"), type: "image", tags: ["QQ", "惊恐"] },
    { id: "qq-27", faceId: "27", name: "流汗", description: "流汗", path: cdn("27", "apng"), fallback: localPng("27"), type: "image", tags: ["QQ", "流汗"] },
    { id: "qq-28", faceId: "28", name: "憨笑", description: "憨笑", path: cdn("28", "apng"), fallback: localPng("28"), type: "image", tags: ["QQ", "憨笑"] },
    { id: "qq-29", faceId: "29", name: "悠闲", description: "悠闲", path: cdn("29", "apng"), fallback: localPng("29"), type: "image", tags: ["QQ", "悠闲"] },
    { id: "qq-30", faceId: "30", name: "奋斗", description: "奋斗", path: cdn("30", "apng"), fallback: localPng("30"), type: "image", tags: ["QQ", "奋斗"] },
    { id: "qq-31", faceId: "31", name: "咒骂", description: "咒骂", path: cdn("31", "apng"), fallback: localPng("31"), type: "image", tags: ["QQ", "咒骂"] },
    { id: "qq-32", faceId: "32", name: "疑问", description: "疑问", path: cdn("32", "apng"), fallback: localPng("32"), type: "image", tags: ["QQ", "疑问"] },
    { id: "qq-33", faceId: "33", name: "嘘", description: "嘘", path: cdn("33", "apng"), fallback: localPng("33"), type: "image", tags: ["QQ", "嘘"] },
    { id: "qq-34", faceId: "34", name: "晕", description: "晕", path: cdn("34", "apng"), fallback: localPng("34"), type: "image", tags: ["QQ", "晕"] },
    { id: "qq-35", faceId: "35", name: "折磨", description: "折磨", path: cdn("35", "apng"), fallback: localPng("35"), type: "image", tags: ["QQ", "折磨"] },
    { id: "qq-36", faceId: "36", name: "衰", description: "衰", path: cdn("36", "apng"), fallback: localPng("36"), type: "image", tags: ["QQ", "衰"] },
    { id: "qq-37", faceId: "37", name: "骷髅", description: "骷髅", path: cdn("37", "apng"), fallback: localPng("37"), type: "image", tags: ["QQ", "骷髅"] },
    { id: "qq-38", faceId: "38", name: "敲打", description: "敲打", path: cdn("38", "apng"), fallback: localPng("38"), type: "image", tags: ["QQ", "敲打"] },
    { id: "qq-39", faceId: "39", name: "再见", description: "再见", path: cdn("39", "apng"), fallback: localPng("39"), type: "image", tags: ["QQ", "再见"] },
    { id: "qq-41", faceId: "41", name: "发抖", description: "发抖", path: cdn("41", "apng"), fallback: localPng("41"), type: "image", tags: ["QQ", "发抖"] },
    { id: "qq-42", faceId: "42", name: "爱情", description: "爱情", path: cdn("42", "apng"), fallback: localPng("42"), type: "image", tags: ["QQ", "爱情"] },
    { id: "qq-43", faceId: "43", name: "跳跳", description: "跳跳", path: cdn("43", "apng"), fallback: localPng("43"), type: "image", tags: ["QQ", "跳跳"] },
    { id: "qq-46", faceId: "46", name: "猪头", description: "猪头", path: cdn("46", "apng"), fallback: localPng("46"), type: "image", tags: ["QQ", "猪头"] },
    { id: "qq-49", faceId: "49", name: "拥抱", description: "拥抱", path: cdn("49", "apng"), fallback: localPng("49"), type: "image", tags: ["QQ", "拥抱"] },
    { id: "qq-53", faceId: "53", name: "蛋糕", description: "蛋糕", path: cdn("53", "apng"), fallback: localPng("53"), type: "image", tags: ["QQ", "蛋糕"] },
    { id: "qq-56", faceId: "56", name: "刀", description: "刀", path: cdn("56", "apng"), fallback: localPng("56"), type: "image", tags: ["QQ", "刀"] },
    { id: "qq-59", faceId: "59", name: "便便", description: "便便", path: cdn("59", "apng"), fallback: localPng("59"), type: "image", tags: ["QQ", "便便"] },
    { id: "qq-60", faceId: "60", name: "咖啡", description: "咖啡", path: cdn("60", "apng"), fallback: localPng("60"), type: "image", tags: ["QQ", "咖啡"] },
    { id: "qq-63", faceId: "63", name: "玫瑰", description: "玫瑰", path: cdn("63", "apng"), fallback: localPng("63"), type: "image", tags: ["QQ", "玫瑰"] },
    { id: "qq-64", faceId: "64", name: "凋谢", description: "凋谢", path: cdn("64", "apng"), fallback: localPng("64"), type: "image", tags: ["QQ", "凋谢"] },
    { id: "qq-66", faceId: "66", name: "爱心", description: "爱心", path: cdn("66", "apng"), fallback: localPng("66"), type: "image", tags: ["QQ", "爱心"] },
    { id: "qq-67", faceId: "67", name: "心碎", description: "心碎", path: cdn("67", "apng"), fallback: localPng("67"), type: "image", tags: ["QQ", "心碎"] },
    { id: "qq-74", faceId: "74", name: "太阳", description: "太阳", path: cdn("74", "apng"), fallback: localPng("74"), type: "image", tags: ["QQ", "太阳"] },
    { id: "qq-75", faceId: "75", name: "月亮", description: "月亮", path: cdn("75", "apng"), fallback: localPng("75"), type: "image", tags: ["QQ", "月亮"] },
    { id: "qq-76", faceId: "76", name: "赞", description: "赞", path: cdn("76", "apng"), fallback: localPng("76"), type: "image", tags: ["QQ", "赞"] },
    { id: "qq-77", faceId: "77", name: "踩", description: "踩", path: cdn("77", "apng"), fallback: localPng("77"), type: "image", tags: ["QQ", "踩"] },
    { id: "qq-78", faceId: "78", name: "握手", description: "握手", path: cdn("78", "apng"), fallback: localPng("78"), type: "image", tags: ["QQ", "握手"] },
    { id: "qq-79", faceId: "79", name: "胜利", description: "胜利", path: cdn("79", "apng"), fallback: localPng("79"), type: "image", tags: ["QQ", "胜利"] },
    { id: "qq-85", faceId: "85", name: "飞吻", description: "飞吻", path: cdn("85", "apng"), fallback: localPng("85"), type: "image", tags: ["QQ", "飞吻"] },
    { id: "qq-86", faceId: "86", name: "怄火", description: "怄火", path: cdn("86", "apng"), fallback: localPng("86"), type: "image", tags: ["QQ", "怄火"] },
    { id: "qq-89", faceId: "89", name: "西瓜", description: "西瓜", path: cdn("89", "apng"), fallback: localPng("89"), type: "image", tags: ["QQ", "西瓜"] },
    { id: "qq-96", faceId: "96", name: "冷汗", description: "冷汗", path: cdn("96", "apng"), fallback: localPng("96"), type: "image", tags: ["QQ", "冷汗"] },
    { id: "qq-97", faceId: "97", name: "擦汗", description: "擦汗", path: cdn("97", "apng"), fallback: localPng("97"), type: "image", tags: ["QQ", "擦汗"] },
    { id: "qq-98", faceId: "98", name: "抠鼻", description: "抠鼻", path: cdn("98", "apng"), fallback: localPng("98"), type: "image", tags: ["QQ", "抠鼻"] },
    { id: "qq-99", faceId: "99", name: "鼓掌", description: "鼓掌", path: cdn("99", "apng"), fallback: localPng("99"), type: "image", tags: ["QQ", "鼓掌"] },
    { id: "qq-100", faceId: "100", name: "糗大了", description: "糗大了", path: cdn("100", "apng"), fallback: localPng("100"), type: "image", tags: ["QQ", "糗大了"] },
    { id: "qq-101", faceId: "101", name: "坏笑", description: "坏笑", path: cdn("101", "apng"), fallback: localPng("101"), type: "image", tags: ["QQ", "坏笑"] },
    { id: "qq-102", faceId: "102", name: "左哼哼", description: "左哼哼", path: cdn("102", "apng"), fallback: localPng("102"), type: "image", tags: ["QQ", "左哼哼"] },
    { id: "qq-103", faceId: "103", name: "右哼哼", description: "右哼哼", path: cdn("103", "apng"), fallback: localPng("103"), type: "image", tags: ["QQ", "右哼哼"] },
    { id: "qq-104", faceId: "104", name: "哈欠", description: "哈欠", path: cdn("104", "apng"), fallback: localPng("104"), type: "image", tags: ["QQ", "哈欠"] },
    { id: "qq-105", faceId: "105", name: "鄙视", description: "鄙视", path: cdn("105", "apng"), fallback: localPng("105"), type: "image", tags: ["QQ", "鄙视"] },
    { id: "qq-106", faceId: "106", name: "委屈", description: "委屈", path: cdn("106", "apng"), fallback: localPng("106"), type: "image", tags: ["QQ", "委屈"] },
    { id: "qq-107", faceId: "107", name: "快哭了", description: "快哭了", path: cdn("107", "apng"), fallback: localPng("107"), type: "image", tags: ["QQ", "快哭了"] },
    { id: "qq-108", faceId: "108", name: "阴险", description: "阴险", path: cdn("108", "apng"), fallback: localPng("108"), type: "image", tags: ["QQ", "阴险"] },
    { id: "qq-109", faceId: "109", name: "左亲亲", description: "左亲亲", path: cdn("109", "apng"), fallback: localPng("109"), type: "image", tags: ["QQ", "左亲亲"] },
    { id: "qq-110", faceId: "110", name: "吓", description: "吓", path: cdn("110", "apng"), fallback: localPng("110"), type: "image", tags: ["QQ", "吓"] },
    { id: "qq-111", faceId: "111", name: "可怜", description: "可怜", path: cdn("111", "apng"), fallback: localPng("111"), type: "image", tags: ["QQ", "可怜"] },
    { id: "qq-112", faceId: "112", name: "菜刀", description: "菜刀", path: cdn("112", "apng"), fallback: localPng("112"), type: "image", tags: ["QQ", "菜刀"] },
    { id: "qq-114", faceId: "114", name: "篮球", description: "篮球", path: cdn("114", "apng"), fallback: localPng("114"), type: "image", tags: ["QQ", "篮球"] },
    { id: "qq-116", faceId: "116", name: "示爱", description: "示爱", path: cdn("116", "apng"), fallback: localPng("116"), type: "image", tags: ["QQ", "示爱"] },
    { id: "qq-118", faceId: "118", name: "抱拳", description: "抱拳", path: cdn("118", "apng"), fallback: localPng("118"), type: "image", tags: ["QQ", "抱拳"] },
    { id: "qq-119", faceId: "119", name: "勾引", description: "勾引", path: cdn("119", "apng"), fallback: localPng("119"), type: "image", tags: ["QQ", "勾引"] },
    { id: "qq-120", faceId: "120", name: "拳头", description: "拳头", path: cdn("120", "apng"), fallback: localPng("120"), type: "image", tags: ["QQ", "拳头"] },
    { id: "qq-121", faceId: "121", name: "差劲", description: "差劲", path: cdn("121", "apng"), fallback: localPng("121"), type: "image", tags: ["QQ", "差劲"] },
    { id: "qq-123", faceId: "123", name: "NO", description: "NO", path: cdn("123", "apng"), fallback: localPng("123"), type: "image", tags: ["QQ", "NO"] },
    { id: "qq-124", faceId: "124", name: "OK", description: "OK", path: cdn("124", "apng"), fallback: localPng("124"), type: "image", tags: ["QQ", "OK"] },
    { id: "qq-125", faceId: "125", name: "转圈", description: "转圈", path: cdn("125", "apng"), fallback: localPng("125"), type: "image", tags: ["QQ", "转圈"] },
    { id: "qq-129", faceId: "129", name: "挥手", description: "挥手", path: cdn("129", "apng"), fallback: localPng("129"), type: "image", tags: ["QQ", "挥手"] },
    { id: "qq-137", faceId: "137", name: "鞭炮", description: "鞭炮", path: cdn("137", "apng"), fallback: localPng("137"), type: "image", tags: ["QQ", "鞭炮"] },
    { id: "qq-144", faceId: "144", name: "喝彩", description: "喝彩", path: cdn("144", "apng"), fallback: localPng("144"), type: "image", tags: ["QQ", "喝彩"] },
    { id: "qq-146", faceId: "146", name: "爆筋", description: "爆筋", path: cdn("146", "apng"), fallback: localPng("146"), type: "image", tags: ["QQ", "爆筋"] },
    { id: "qq-147", faceId: "147", name: "棒棒糖", description: "棒棒糖", path: cdn("147", "apng"), fallback: localPng("147"), type: "image", tags: ["QQ", "棒棒糖"] },
    { id: "qq-169", faceId: "169", name: "手枪", description: "手枪", path: cdn("169", "apng"), fallback: localPng("169"), type: "image", tags: ["QQ", "手枪"] },
    { id: "qq-171", faceId: "171", name: "茶", description: "茶", path: cdn("171", "apng"), fallback: localPng("171"), type: "image", tags: ["QQ", "茶"] },
    { id: "qq-172", faceId: "172", name: "眨眼睛", description: "眨眼睛", path: cdn("172", "apng"), fallback: localPng("172"), type: "image", tags: ["QQ", "眨眼睛"] },
    { id: "qq-173", faceId: "173", name: "泪奔", description: "泪奔", path: cdn("173", "apng"), fallback: localPng("173"), type: "image", tags: ["QQ", "泪奔"] },
    { id: "qq-174", faceId: "174", name: "无奈", description: "无奈", path: cdn("174", "apng"), fallback: localPng("174"), type: "image", tags: ["QQ", "无奈"] },
    { id: "qq-175", faceId: "175", name: "卖萌", description: "卖萌", path: cdn("175", "apng"), fallback: localPng("175"), type: "image", tags: ["QQ", "卖萌"] },
    { id: "qq-176", faceId: "176", name: "小纠结", description: "小纠结", path: cdn("176", "apng"), fallback: localPng("176"), type: "image", tags: ["QQ", "小纠结"] },
    { id: "qq-177", faceId: "177", name: "喷血", description: "喷血", path: cdn("177", "apng"), fallback: localPng("177"), type: "image", tags: ["QQ", "喷血"] },
    { id: "qq-178", faceId: "178", name: "斜眼笑", description: "斜眼笑", path: cdn("178", "apng"), fallback: localPng("178"), type: "image", tags: ["QQ", "斜眼笑"] },
    { id: "qq-179", faceId: "179", name: "doge", description: "doge", path: cdn("179", "apng"), fallback: localPng("179"), type: "image", tags: ["QQ", "doge"] },
    { id: "qq-181", faceId: "181", name: "戳一戳", description: "戳一戳", path: cdn("181", "apng"), fallback: localPng("181"), type: "image", tags: ["QQ", "戳一戳"] },
    { id: "qq-182", faceId: "182", name: "笑哭", description: "笑哭", path: cdn("182", "apng"), fallback: localPng("182"), type: "image", tags: ["QQ", "笑哭"] },
    { id: "qq-183", faceId: "183", name: "我最美", description: "我最美", path: cdn("183", "apng"), fallback: localPng("183"), type: "image", tags: ["QQ", "我最美"] },
    { id: "qq-185", faceId: "185", name: "羊驼", description: "羊驼", path: cdn("185", "apng"), fallback: localPng("185"), type: "image", tags: ["QQ", "羊驼"] },
    { id: "qq-187", faceId: "187", name: "幽灵", description: "幽灵", path: cdn("187", "apng"), fallback: localPng("187"), type: "image", tags: ["QQ", "幽灵"] },
    { id: "qq-201", faceId: "201", name: "点赞", description: "点赞", path: cdn("201", "apng"), fallback: localPng("201"), type: "image", tags: ["QQ", "点赞"] },
    { id: "qq-212", faceId: "212", name: "托腮", description: "托腮", path: cdn("212", "apng"), fallback: localPng("212"), type: "image", tags: ["QQ", "托腮"] },
    { id: "qq-262", faceId: "262", name: "脑阔疼", description: "脑阔疼", path: cdn("262", "apng"), fallback: localPng("262"), type: "image", tags: ["QQ", "脑阔疼"] },
    { id: "qq-263", faceId: "263", name: "沧桑", description: "沧桑", path: cdn("263", "apng"), fallback: localPng("263"), type: "image", tags: ["QQ", "沧桑"] },
    { id: "qq-264", faceId: "264", name: "捂脸", description: "捂脸", path: cdn("264", "apng"), fallback: localPng("264"), type: "image", tags: ["QQ", "捂脸"] },
    { id: "qq-265", faceId: "265", name: "辣眼睛", description: "辣眼睛", path: cdn("265", "apng"), fallback: localPng("265"), type: "image", tags: ["QQ", "辣眼睛"] },
    { id: "qq-266", faceId: "266", name: "哦哟", description: "哦哟", path: cdn("266", "apng"), fallback: localPng("266"), type: "image", tags: ["QQ", "哦哟"] },
    { id: "qq-267", faceId: "267", name: "头秃", description: "头秃", path: cdn("267", "apng"), fallback: localPng("267"), type: "image", tags: ["QQ", "头秃"] },
    { id: "qq-268", faceId: "268", name: "问号脸", description: "问号脸", path: cdn("268", "apng"), fallback: localPng("268"), type: "image", tags: ["QQ", "问号脸"] },
    { id: "qq-269", faceId: "269", name: "暗中观察", description: "暗中观察", path: cdn("269", "apng"), fallback: localPng("269"), type: "image", tags: ["QQ", "暗中观察"] },
    { id: "qq-270", faceId: "270", name: "emm", description: "emm", path: cdn("270", "apng"), fallback: localPng("270"), type: "image", tags: ["QQ", "emm"] },
    { id: "qq-271", faceId: "271", name: "吃瓜", description: "吃瓜", path: cdn("271", "apng"), fallback: localPng("271"), type: "image", tags: ["QQ", "吃瓜"] },
    { id: "qq-272", faceId: "272", name: "呵呵哒", description: "呵呵哒", path: cdn("272", "apng"), fallback: localPng("272"), type: "image", tags: ["QQ", "呵呵哒"] },
    { id: "qq-273", faceId: "273", name: "我酸了", description: "我酸了", path: cdn("273", "apng"), fallback: localPng("273"), type: "image", tags: ["QQ", "我酸了"] },
    { id: "qq-277", faceId: "277", name: "汪汪", description: "汪汪", path: cdn("277", "apng"), fallback: localPng("277"), type: "image", tags: ["QQ", "汪汪"] },
    { id: "qq-281", faceId: "281", name: "无眼笑", description: "无眼笑", path: cdn("281", "apng"), fallback: localPng("281"), type: "image", tags: ["QQ", "无眼笑"] },
    { id: "qq-282", faceId: "282", name: "敬礼", description: "敬礼", path: cdn("282", "apng"), fallback: localPng("282"), type: "image", tags: ["QQ", "敬礼"] },
    { id: "qq-283", faceId: "283", name: "狂笑", description: "狂笑", path: cdn("283", "apng"), fallback: localPng("283"), type: "image", tags: ["QQ", "狂笑"] },
    { id: "qq-284", faceId: "284", name: "面无表情", description: "面无表情", path: cdn("284", "apng"), fallback: localPng("284"), type: "image", tags: ["QQ", "面无表情"] },
    { id: "qq-285", faceId: "285", name: "摸鱼", description: "摸鱼", path: cdn("285", "apng"), fallback: localPng("285"), type: "image", tags: ["QQ", "摸鱼"] },
    { id: "qq-286", faceId: "286", name: "魔鬼笑", description: "魔鬼笑", path: cdn("286", "apng"), fallback: localPng("286"), type: "image", tags: ["QQ", "魔鬼笑"] },
    { id: "qq-287", faceId: "287", name: "哦", description: "哦", path: cdn("287", "apng"), fallback: localPng("287"), type: "image", tags: ["QQ", "哦"] },
    { id: "qq-289", faceId: "289", name: "睁眼", description: "睁眼", path: cdn("289", "apng"), fallback: localPng("289"), type: "image", tags: ["QQ", "睁眼"] },
    { id: "qq-293", faceId: "293", name: "摸锦鲤", description: "摸锦鲤", path: cdn("293", "apng"), fallback: localPng("293"), type: "image", tags: ["QQ", "摸锦鲤"] },
    { id: "qq-294", faceId: "294", name: "期待", description: "期待", path: cdn("294", "apng"), fallback: localPng("294"), type: "image", tags: ["QQ", "期待"] },
    { id: "qq-295", faceId: "295", name: "拿到红包", description: "拿到红包", path: cdn("295", "apng"), fallback: localPng("295"), type: "image", tags: ["QQ", "拿到红包"] },
    { id: "qq-297", faceId: "297", name: "拜谢", description: "拜谢", path: cdn("297", "apng"), fallback: localPng("297"), type: "image", tags: ["QQ", "拜谢"] },
    { id: "qq-298", faceId: "298", name: "元宝", description: "元宝", path: cdn("298", "apng"), fallback: localPng("298"), type: "image", tags: ["QQ", "元宝"] },
    { id: "qq-299", faceId: "299", name: "牛啊", description: "牛啊", path: cdn("299", "apng"), fallback: localPng("299"), type: "image", tags: ["QQ", "牛啊"] },
    { id: "qq-300", faceId: "300", name: "胖三斤", description: "胖三斤", path: cdn("300", "apng"), fallback: localPng("300"), type: "image", tags: ["QQ", "胖三斤"] },
    { id: "qq-302", faceId: "302", name: "左拜年", description: "左拜年", path: cdn("302", "apng"), fallback: localPng("302"), type: "image", tags: ["QQ", "左拜年"] },
    { id: "qq-303", faceId: "303", name: "右拜年", description: "右拜年", path: cdn("303", "apng"), fallback: localPng("303"), type: "image", tags: ["QQ", "右拜年"] },
    { id: "qq-305", faceId: "305", name: "右亲亲", description: "右亲亲", path: cdn("305", "apng"), fallback: localPng("305"), type: "image", tags: ["QQ", "右亲亲"] },
    { id: "qq-306", faceId: "306", name: "牛气冲天", description: "牛气冲天", path: cdn("306", "apng"), fallback: localPng("306"), type: "image", tags: ["QQ", "牛气冲天"] },
    { id: "qq-307", faceId: "307", name: "喵喵", description: "喵喵", path: cdn("307", "apng"), fallback: localPng("307"), type: "image", tags: ["QQ", "喵喵"] },
    { id: "qq-311", faceId: "311", name: "打call", description: "打call", path: cdn("311", "apng"), fallback: localPng("311"), type: "image", tags: ["QQ", "打call"] },
    { id: "qq-312", faceId: "312", name: "变形", description: "变形", path: cdn("312", "apng"), fallback: localPng("312"), type: "image", tags: ["QQ", "变形"] },
    { id: "qq-314", faceId: "314", name: "仔细分析", description: "仔细分析", path: cdn("314", "apng"), fallback: localPng("314"), type: "image", tags: ["QQ", "仔细分析"] },
    { id: "qq-317", faceId: "317", name: "菜汪", description: "菜汪", path: cdn("317", "apng"), fallback: localPng("317"), type: "image", tags: ["QQ", "菜汪"] },
    { id: "qq-318", faceId: "318", name: "崇拜", description: "崇拜", path: cdn("318", "apng"), fallback: localPng("318"), type: "image", tags: ["QQ", "崇拜"] },
    { id: "qq-319", faceId: "319", name: "比心", description: "比心", path: cdn("319", "apng"), fallback: localPng("319"), type: "image", tags: ["QQ", "比心"] },
    { id: "qq-320", faceId: "320", name: "庆祝", description: "庆祝", path: cdn("320", "apng"), fallback: localPng("320"), type: "image", tags: ["QQ", "庆祝"] },
    { id: "qq-323", faceId: "323", name: "嫌弃", description: "嫌弃", path: cdn("323", "apng"), fallback: localPng("323"), type: "image", tags: ["QQ", "嫌弃"] },
    { id: "qq-324", faceId: "324", name: "吃糖", description: "吃糖", path: cdn("324", "apng"), fallback: localPng("324"), type: "image", tags: ["QQ", "吃糖"] },
    { id: "qq-325", faceId: "325", name: "惊吓", description: "惊吓", path: cdn("325", "apng"), fallback: localPng("325"), type: "image", tags: ["QQ", "惊吓"] },
    { id: "qq-326", faceId: "326", name: "生气", description: "生气", path: cdn("326", "apng"), fallback: localPng("326"), type: "image", tags: ["QQ", "生气"] },
    { id: "qq-332", faceId: "332", name: "举牌牌", description: "举牌牌", path: cdn("332", "apng"), fallback: localPng("332"), type: "image", tags: ["QQ", "举牌牌"] },
    { id: "qq-333", faceId: "333", name: "烟花", description: "烟花", path: cdn("333", "apng"), fallback: localPng("333"), type: "image", tags: ["QQ", "烟花"] },
    { id: "qq-334", faceId: "334", name: "虎虎生威", description: "虎虎生威", path: cdn("334", "apng"), fallback: localPng("334"), type: "image", tags: ["QQ", "虎虎生威"] },
    { id: "qq-336", faceId: "336", name: "豹富", description: "豹富", path: cdn("336", "apng"), fallback: localPng("336"), type: "image", tags: ["QQ", "豹富"] },
    { id: "qq-337", faceId: "337", name: "花朵脸", description: "花朵脸", path: cdn("337", "apng"), fallback: localPng("337"), type: "image", tags: ["QQ", "花朵脸"] },
    { id: "qq-338", faceId: "338", name: "我想开了", description: "我想开了", path: cdn("338", "apng"), fallback: localPng("338"), type: "image", tags: ["QQ", "我想开了"] },
    { id: "qq-339", faceId: "339", name: "舔屏", description: "舔屏", path: cdn("339", "apng"), fallback: localPng("339"), type: "image", tags: ["QQ", "舔屏"] },
    { id: "qq-341", faceId: "341", name: "打招呼", description: "打招呼", path: cdn("341", "apng"), fallback: localPng("341"), type: "image", tags: ["QQ", "打招呼"] },
    { id: "qq-342", faceId: "342", name: "酸Q", description: "酸Q", path: cdn("342", "apng"), fallback: localPng("342"), type: "image", tags: ["QQ", "酸Q"] },
    { id: "qq-343", faceId: "343", name: "我方了", description: "我方了", path: cdn("343", "apng"), fallback: localPng("343"), type: "image", tags: ["QQ", "我方了"] },
    { id: "qq-344", faceId: "344", name: "大怨种", description: "大怨种", path: cdn("344", "apng"), fallback: localPng("344"), type: "image", tags: ["QQ", "大怨种"] },
    { id: "qq-345", faceId: "345", name: "红包多多", description: "红包多多", path: cdn("345", "apng"), fallback: localPng("345"), type: "image", tags: ["QQ", "红包多多"] },
    { id: "qq-346", faceId: "346", name: "你真棒棒", description: "你真棒棒", path: cdn("346", "apng"), fallback: localPng("346"), type: "image", tags: ["QQ", "你真棒棒"] },
    { id: "qq-347", faceId: "347", name: "大展宏兔", description: "大展宏兔", path: cdn("347", "apng"), fallback: localPng("347"), type: "image", tags: ["QQ", "大展宏兔"] },
    { id: "qq-349", faceId: "349", name: "坚强", description: "坚强", path: cdn("349", "apng"), fallback: localPng("349"), type: "image", tags: ["QQ", "坚强"] },
    { id: "qq-350", faceId: "350", name: "贴贴", description: "贴贴", path: cdn("350", "apng"), fallback: localPng("350"), type: "image", tags: ["QQ", "贴贴"] },
    { id: "qq-351", faceId: "351", name: "敲敲", description: "敲敲", path: cdn("351", "apng"), fallback: localPng("351"), type: "image", tags: ["QQ", "敲敲"] },
    { id: "qq-352", faceId: "352", name: "咦", description: "咦", path: cdn("352", "apng"), fallback: localPng("352"), type: "image", tags: ["QQ", "咦"] },
    { id: "qq-353", faceId: "353", name: "拜托", description: "拜托", path: cdn("353", "apng"), fallback: localPng("353"), type: "image", tags: ["QQ", "拜托"] },
    { id: "qq-354", faceId: "354", name: "尊嘟假嘟", description: "尊嘟假嘟", path: cdn("354", "apng"), fallback: localPng("354"), type: "image", tags: ["QQ", "尊嘟假嘟"] },
    { id: "qq-355", faceId: "355", name: "耶", description: "耶", path: cdn("355", "apng"), fallback: localPng("355"), type: "image", tags: ["QQ", "耶"] },
    { id: "qq-356", faceId: "356", name: "666", description: "666", path: cdn("356", "apng"), fallback: localPng("356"), type: "image", tags: ["QQ", "666"] },
    { id: "qq-357", faceId: "357", name: "裂开", description: "裂开", path: cdn("357", "apng"), fallback: localPng("357"), type: "image", tags: ["QQ", "裂开"] },
    { id: "qq-392", faceId: "392", name: "龙年快乐", description: "龙年快乐", path: cdn("392", "apng"), fallback: localPng("392"), type: "image", tags: ["QQ", "龙年快乐"] },
    { id: "qq-395", faceId: "395", name: "略略略", description: "略略略", path: cdn("395", "apng"), fallback: localPng("395"), type: "image", tags: ["QQ", "略略略"] },
    { id: "qq-415", faceId: "415", name: "划龙舟", description: "划龙舟", path: cdn("415", "apng"), fallback: localPng("415"), type: "image", tags: ["QQ", "划龙舟"] },
    { id: "qq-419", faceId: "419", name: "火车", description: "火车", path: cdn("419", "apng"), fallback: localPng("419"), type: "image", tags: ["QQ", "火车"] },
    { id: "qq-422", faceId: "422", name: "表情422", description: "表情422", path: cdn("422", "apng"), fallback: localPng("422"), type: "image", tags: ["QQ", "表情422"] },
    { id: "qq-423", faceId: "423", name: "表情423", description: "表情423", path: cdn("423", "apng"), fallback: localPng("423"), type: "image", tags: ["QQ", "表情423"] },
    { id: "qq-424", faceId: "424", name: "续标识", description: "续标识", path: cdn("424", "apng"), fallback: localPng("424"), type: "image", tags: ["QQ", "续标识"] },
    { id: "qq-425", faceId: "425", name: "求放过", description: "求放过", path: cdn("425", "apng"), fallback: localPng("425"), type: "image", tags: ["QQ", "求放过"] },
    { id: "qq-426", faceId: "426", name: "玩火", description: "玩火", path: cdn("426", "apng"), fallback: localPng("426"), type: "image", tags: ["QQ", "玩火"] },
    { id: "qq-427", faceId: "427", name: "偷感", description: "偷感", path: cdn("427", "apng"), fallback: localPng("427"), type: "image", tags: ["QQ", "偷感"] },
    { id: "qq-428", faceId: "428", name: "收到", description: "收到", path: cdn("428", "apng"), fallback: localPng("428"), type: "image", tags: ["QQ", "收到"] },
    { id: "qq-429", faceId: "429", name: "蛇年快乐", description: "蛇年快乐", path: cdn("429", "apng"), fallback: localPng("429"), type: "image", tags: ["QQ", "蛇年快乐"] },
    { id: "qq-432", faceId: "432", name: "表情432", description: "表情432", path: cdn("432", "apng"), fallback: localPng("432"), type: "image", tags: ["QQ", "表情432"] },
    { id: "qq-450", faceId: "450", name: "表情450", description: "表情450", path: cdn("450", "apng"), fallback: localPng("450"), type: "image", tags: ["QQ", "表情450"] },
    { id: "qq-451", faceId: "451", name: "表情451", description: "表情451", path: cdn("451", "apng"), fallback: localPng("451"), type: "image", tags: ["QQ", "表情451"] },
    { id: "qq-452", faceId: "452", name: "表情452", description: "表情452", path: cdn("452", "apng"), fallback: localPng("452"), type: "image", tags: ["QQ", "表情452"] },
    { id: "qq-453", faceId: "453", name: "表情453", description: "表情453", path: cdn("453", "apng"), fallback: localPng("453"), type: "image", tags: ["QQ", "表情453"] },
    { id: "qq-454", faceId: "454", name: "表情454", description: "表情454", path: cdn("454", "apng"), fallback: localPng("454"), type: "image", tags: ["QQ", "表情454"] },
    { id: "qq-455", faceId: "455", name: "表情455", description: "表情455", path: cdn("455", "apng"), fallback: localPng("455"), type: "image", tags: ["QQ", "表情455"] },
    { id: "qq-456", faceId: "456", name: "表情456", description: "表情456", path: cdn("456", "apng"), fallback: localPng("456"), type: "image", tags: ["QQ", "表情456"] },
    { id: "qq-457", faceId: "457", name: "表情457", description: "表情457", path: cdn("457", "apng"), fallback: localPng("457"), type: "image", tags: ["QQ", "表情457"] },
    { id: "qq-458", faceId: "458", name: "表情458", description: "表情458", path: cdn("458", "apng"), fallback: localPng("458"), type: "image", tags: ["QQ", "表情458"] },
    { id: "qq-459", faceId: "459", name: "表情459", description: "表情459", path: cdn("459", "apng"), fallback: localPng("459"), type: "image", tags: ["QQ", "表情459"] },
    { id: "qq-460", faceId: "460", name: "表情460", description: "表情460", path: cdn("460", "apng"), fallback: localPng("460"), type: "image", tags: ["QQ", "表情460"] },
    { id: "qq-461", faceId: "461", name: "表情461", description: "表情461", path: cdn("461", "apng"), fallback: localPng("461"), type: "image", tags: ["QQ", "表情461"] },
    { id: "qq-462", faceId: "462", name: "表情462", description: "表情462", path: cdn("462", "apng"), fallback: localPng("462"), type: "image", tags: ["QQ", "表情462"] },
    { id: "qq-463", faceId: "463", name: "表情463", description: "表情463", path: cdn("463", "apng"), fallback: localPng("463"), type: "image", tags: ["QQ", "表情463"] },
    { id: "qq-464", faceId: "464", name: "表情464", description: "表情464", path: cdn("464", "apng"), fallback: localPng("464"), type: "image", tags: ["QQ", "表情464"] },
    { id: "qq-465", faceId: "465", name: "表情465", description: "表情465", path: cdn("465", "apng"), fallback: localPng("465"), type: "image", tags: ["QQ", "表情465"] },
    { id: "qq-466", faceId: "466", name: "表情466", description: "表情466", path: cdn("466", "apng"), fallback: localPng("466"), type: "image", tags: ["QQ", "表情466"] },
    { id: "qq-467", faceId: "467", name: "表情467", description: "表情467", path: cdn("467", "apng"), fallback: localPng("467"), type: "image", tags: ["QQ", "表情467"] },
    { id: "qq-468", faceId: "468", name: "表情468", description: "表情468", path: cdn("468", "apng"), fallback: localPng("468"), type: "image", tags: ["QQ", "表情468"] },
    { id: "qq-469", faceId: "469", name: "表情469", description: "表情469", path: cdn("469", "apng"), fallback: localPng("469"), type: "image", tags: ["QQ", "表情469"] },
    { id: "qq-470", faceId: "470", name: "表情470", description: "表情470", path: cdn("470", "apng"), fallback: localPng("470"), type: "image", tags: ["QQ", "表情470"] },
    { id: "qq-472", faceId: "472", name: "表情472", description: "表情472", path: cdn("472", "apng"), fallback: localPng("472"), type: "image", tags: ["QQ", "表情472"] },
    { id: "qq-474", faceId: "474", name: "表情474", description: "表情474", path: cdn("474", "apng"), fallback: localPng("474"), type: "image", tags: ["QQ", "表情474"] },
    { id: "qq-475", faceId: "475", name: "表情475", description: "表情475", path: cdn("475", "apng"), fallback: localPng("475"), type: "image", tags: ["QQ", "表情475"] },
    { id: "qq-476", faceId: "476", name: "表情476", description: "表情476", path: cdn("476", "apng"), fallback: localPng("476"), type: "image", tags: ["QQ", "表情476"] },
    { id: "qq-477", faceId: "477", name: "表情477", description: "表情477", path: cdn("477", "apng"), fallback: localPng("477"), type: "image", tags: ["QQ", "表情477"] },
    { id: "qq-478", faceId: "478", name: "表情478", description: "表情478", path: cdn("478", "apng"), fallback: localPng("478"), type: "image", tags: ["QQ", "表情478"] },
    { id: "qq-479", faceId: "479", name: "表情479", description: "表情479", path: cdn("479", "apng"), fallback: localPng("479"), type: "image", tags: ["QQ", "表情479"] },
    { id: "qq-480", faceId: "480", name: "表情480", description: "表情480", path: cdn("480", "apng"), fallback: localPng("480"), type: "image", tags: ["QQ", "表情480"] },
    { id: "qq-481", faceId: "481", name: "表情481", description: "表情481", path: cdn("481", "apng"), fallback: localPng("481"), type: "image", tags: ["QQ", "表情481"] },
    { id: "qq-482", faceId: "482", name: "表情482", description: "表情482", path: cdn("482", "apng"), fallback: localPng("482"), type: "image", tags: ["QQ", "表情482"] },
    { id: "qq-483", faceId: "483", name: "表情483", description: "表情483", path: cdn("483", "apng"), fallback: localPng("483"), type: "image", tags: ["QQ", "表情483"] },
    { id: "qq-484", faceId: "484", name: "表情484", description: "表情484", path: cdn("484", "apng"), fallback: localPng("484"), type: "image", tags: ["QQ", "表情484"] },
    { id: "qq-485", faceId: "485", name: "表情485", description: "表情485", path: cdn("485", "apng"), fallback: localPng("485"), type: "image", tags: ["QQ", "表情485"] },
    { id: "qq-488", faceId: "488", name: "表情488", description: "表情488", path: cdn("488", "apng"), fallback: localPng("488"), type: "image", tags: ["QQ", "表情488"] },
    { id: "qq-489", faceId: "489", name: "表情489", description: "表情489", path: cdn("489", "apng"), fallback: localPng("489"), type: "image", tags: ["QQ", "表情489"] },
    { id: "qq-490", faceId: "490", name: "表情490", description: "表情490", path: cdn("490", "apng"), fallback: localPng("490"), type: "image", tags: ["QQ", "表情490"] },
    { id: "qq-491", faceId: "491", name: "表情491", description: "表情491", path: cdn("491", "apng"), fallback: localPng("491"), type: "image", tags: ["QQ", "表情491"] },
    { id: "qq-492", faceId: "492", name: "表情492", description: "表情492", path: cdn("492", "apng"), fallback: localPng("492"), type: "image", tags: ["QQ", "表情492"] },
    { id: "qq-493", faceId: "493", name: "表情493", description: "表情493", path: cdn("493", "apng"), fallback: localPng("493"), type: "image", tags: ["QQ", "表情493"] },
    { id: "qq-☀", name: "晴天", description: "晴天", path: cdn("☀", "png"), fallback: localPng("☀"), type: "image", tags: ["QQ", "晴天"] },
    { id: "qq-☕", name: "咖啡", description: "咖啡", path: cdn("☕", "png"), fallback: localPng("☕"), type: "image", tags: ["QQ", "咖啡"] },
    { id: "qq-☺", name: "可爱", description: "可爱", path: cdn("☺", "png"), fallback: localPng("☺"), type: "image", tags: ["QQ", "可爱"] },
    { id: "qq-✨", name: "闪光", description: "闪光", path: cdn("✨", "png"), fallback: localPng("✨"), type: "image", tags: ["QQ", "闪光"] },
    { id: "qq-❔", name: "问号", description: "问号", path: cdn("❔", "png"), fallback: localPng("❔"), type: "image", tags: ["QQ", "问号"] },
    { id: "qq-🌹", name: "玫瑰", description: "玫瑰", path: cdn("🌹", "png"), fallback: localPng("🌹"), type: "image", tags: ["QQ", "玫瑰"] },
    { id: "qq-🍉", name: "西瓜", description: "西瓜", path: cdn("🍉", "png"), fallback: localPng("🍉"), type: "image", tags: ["QQ", "西瓜"] },
    { id: "qq-🍎", name: "苹果", description: "苹果", path: cdn("🍎", "png"), fallback: localPng("🍎"), type: "image", tags: ["QQ", "苹果"] },
    { id: "qq-🍓", name: "草莓", description: "草莓", path: cdn("🍓", "png"), fallback: localPng("🍓"), type: "image", tags: ["QQ", "草莓"] },
    { id: "qq-🍜", name: "拉面", description: "拉面", path: cdn("🍜", "png"), fallback: localPng("🍜"), type: "image", tags: ["QQ", "拉面"] },
    { id: "qq-🍞", name: "面包", description: "面包", path: cdn("🍞", "png"), fallback: localPng("🍞"), type: "image", tags: ["QQ", "面包"] },
    { id: "qq-🍧", name: "刨冰", description: "刨冰", path: cdn("🍧", "png"), fallback: localPng("🍧"), type: "image", tags: ["QQ", "刨冰"] },
    { id: "qq-🍺", name: "啤酒", description: "啤酒", path: cdn("🍺", "png"), fallback: localPng("🍺"), type: "image", tags: ["QQ", "啤酒"] },
    { id: "qq-🍻", name: "干杯", description: "干杯", path: cdn("🍻", "png"), fallback: localPng("🍻"), type: "image", tags: ["QQ", "干杯"] },
    { id: "qq-🎉", name: "庆祝", description: "庆祝", path: cdn("🎉", "png"), fallback: localPng("🎉"), type: "image", tags: ["QQ", "庆祝"] },
    { id: "qq-🏪", name: "便利店", description: "便利店", path: cdn("🏪", "png"), fallback: localPng("🏪"), type: "image", tags: ["QQ", "便利店"] },
    { id: "qq-🐎", name: "骑马", description: "骑马", path: cdn("🐎", "png"), fallback: localPng("🐎"), type: "image", tags: ["QQ", "骑马"] },
    { id: "qq-🐔", name: "公鸡", description: "公鸡", path: cdn("🐔", "png"), fallback: localPng("🐔"), type: "image", tags: ["QQ", "公鸡"] },
    { id: "qq-🐛", name: "虫", description: "虫", path: cdn("🐛", "png"), fallback: localPng("🐛"), type: "image", tags: ["QQ", "虫"] },
    { id: "qq-🐮", name: "牛", description: "牛", path: cdn("🐮", "png"), fallback: localPng("🐮"), type: "image", tags: ["QQ", "牛"] },
    { id: "qq-🐳", name: "鲸鱼", description: "鲸鱼", path: cdn("🐳", "png"), fallback: localPng("🐳"), type: "image", tags: ["QQ", "鲸鱼"] },
    { id: "qq-🐵", name: "猴", description: "猴", path: cdn("🐵", "png"), fallback: localPng("🐵"), type: "image", tags: ["QQ", "猴"] },
    { id: "qq-🐶", name: "狗", description: "狗", path: cdn("🐶", "png"), fallback: localPng("🐶"), type: "image", tags: ["QQ", "狗"] },
    { id: "qq-🐷", name: "猪", description: "猪", path: cdn("🐷", "png"), fallback: localPng("🐷"), type: "image", tags: ["QQ", "猪"] },
    { id: "qq-🐸", name: "青蛙", description: "青蛙", path: cdn("🐸", "png"), fallback: localPng("🐸"), type: "image", tags: ["QQ", "青蛙"] },
    { id: "qq-👀", name: "眼睛", description: "眼睛", path: cdn("👀", "png"), fallback: localPng("👀"), type: "image", tags: ["QQ", "眼睛"] },
    { id: "qq-👆", name: "向上", description: "向上", path: cdn("👆", "png"), fallback: localPng("👆"), type: "image", tags: ["QQ", "向上"] },
    { id: "qq-👊", name: "拳头", description: "拳头", path: cdn("👊", "png"), fallback: localPng("👊"), type: "image", tags: ["QQ", "拳头"] },
    { id: "qq-👌", name: "好的", description: "好的", path: cdn("👌", "png"), fallback: localPng("👌"), type: "image", tags: ["QQ", "好的"] },
    { id: "qq-👍", name: "厉害", description: "厉害", path: cdn("👍", "png"), fallback: localPng("👍"), type: "image", tags: ["QQ", "厉害"] },
    { id: "qq-👎", name: "鄙视", description: "鄙视", path: cdn("👎", "png"), fallback: localPng("👎"), type: "image", tags: ["QQ", "鄙视"] },
    { id: "qq-👏", name: "鼓掌", description: "鼓掌", path: cdn("👏", "png"), fallback: localPng("👏"), type: "image", tags: ["QQ", "鼓掌"] },
    { id: "qq-👢", name: "靴子", description: "靴子", path: cdn("👢", "png"), fallback: localPng("👢"), type: "image", tags: ["QQ", "靴子"] },
    { id: "qq-👦", name: "男孩", description: "男孩", path: cdn("👦", "png"), fallback: localPng("👦"), type: "image", tags: ["QQ", "男孩"] },
    { id: "qq-👧", name: "女孩", description: "女孩", path: cdn("👧", "png"), fallback: localPng("👧"), type: "image", tags: ["QQ", "女孩"] },
    { id: "qq-👻", name: "幽灵", description: "幽灵", path: cdn("👻", "png"), fallback: localPng("👻"), type: "image", tags: ["QQ", "幽灵"] },
    { id: "qq-💉", name: "打针", description: "打针", path: cdn("💉", "png"), fallback: localPng("💉"), type: "image", tags: ["QQ", "打针"] },
    { id: "qq-💓", name: "爱心", description: "爱心", path: cdn("💓", "png"), fallback: localPng("💓"), type: "image", tags: ["QQ", "爱心"] },
    { id: "qq-💝", name: "礼物", description: "礼物", path: cdn("💝", "png"), fallback: localPng("💝"), type: "image", tags: ["QQ", "礼物"] },
    { id: "qq-💣", name: "炸弹", description: "炸弹", path: cdn("💣", "png"), fallback: localPng("💣"), type: "image", tags: ["QQ", "炸弹"] },
    { id: "qq-💤", name: "睡觉", description: "睡觉", path: cdn("💤", "png"), fallback: localPng("💤"), type: "image", tags: ["QQ", "睡觉"] },
    { id: "qq-💦", name: "水", description: "水", path: cdn("💦", "png"), fallback: localPng("💦"), type: "image", tags: ["QQ", "水"] },
    { id: "qq-💨", name: "吹气", description: "吹气", path: cdn("💨", "png"), fallback: localPng("💨"), type: "image", tags: ["QQ", "吹气"] },
    { id: "qq-💩", name: "便便", description: "便便", path: cdn("💩", "png"), fallback: localPng("💩"), type: "image", tags: ["QQ", "便便"] },
    { id: "qq-💪", name: "肌肉", description: "肌肉", path: cdn("💪", "png"), fallback: localPng("💪"), type: "image", tags: ["QQ", "肌肉"] },
    { id: "qq-📫", name: "邮箱", description: "邮箱", path: cdn("📫", "png"), fallback: localPng("📫"), type: "image", tags: ["QQ", "邮箱"] },
    { id: "qq-🔥", name: "火", description: "火", path: cdn("🔥", "png"), fallback: localPng("🔥"), type: "image", tags: ["QQ", "火"] },
    { id: "qq-🔫", name: "手枪", description: "手枪", path: cdn("🔫", "png"), fallback: localPng("🔫"), type: "image", tags: ["QQ", "手枪"] },
    { id: "qq-😁", name: "呲牙", description: "呲牙", path: cdn("😁", "png"), fallback: localPng("😁"), type: "image", tags: ["QQ", "呲牙"] },
    { id: "qq-😂", name: "激动", description: "激动", path: cdn("😂", "png"), fallback: localPng("😂"), type: "image", tags: ["QQ", "激动"] },
    { id: "qq-😄", name: "高兴", description: "高兴", path: cdn("😄", "png"), fallback: localPng("😄"), type: "image", tags: ["QQ", "高兴"] },
    { id: "qq-😊", name: "嘿嘿", description: "嘿嘿", path: cdn("😊", "png"), fallback: localPng("😊"), type: "image", tags: ["QQ", "嘿嘿"] },
    { id: "qq-😌", name: "羞涩", description: "羞涩", path: cdn("😌", "png"), fallback: localPng("😌"), type: "image", tags: ["QQ", "羞涩"] },
    { id: "qq-😍", name: "花痴", description: "花痴", path: cdn("😍", "png"), fallback: localPng("😍"), type: "image", tags: ["QQ", "花痴"] },
    { id: "qq-😏", name: "哼哼", description: "哼哼", path: cdn("😏", "png"), fallback: localPng("😏"), type: "image", tags: ["QQ", "哼哼"] },
    { id: "qq-😒", name: "不屑", description: "不屑", path: cdn("😒", "png"), fallback: localPng("😒"), type: "image", tags: ["QQ", "不屑"] },
    { id: "qq-😓", name: "汗", description: "汗", path: cdn("😓", "png"), fallback: localPng("😓"), type: "image", tags: ["QQ", "汗"] },
    { id: "qq-😔", name: "失落", description: "失落", path: cdn("😔", "png"), fallback: localPng("😔"), type: "image", tags: ["QQ", "失落"] },
    { id: "qq-😘", name: "飞吻", description: "飞吻", path: cdn("😘", "png"), fallback: localPng("😘"), type: "image", tags: ["QQ", "飞吻"] },
    { id: "qq-😚", name: "亲亲", description: "亲亲", path: cdn("😚", "png"), fallback: localPng("😚"), type: "image", tags: ["QQ", "亲亲"] },
    { id: "qq-😜", name: "淘气", description: "淘气", path: cdn("😜", "png"), fallback: localPng("😜"), type: "image", tags: ["QQ", "淘气"] },
    { id: "qq-😝", name: "吐舌", description: "吐舌", path: cdn("😝", "png"), fallback: localPng("😝"), type: "image", tags: ["QQ", "吐舌"] },
    { id: "qq-😭", name: "大哭", description: "大哭", path: cdn("😭", "png"), fallback: localPng("😭"), type: "image", tags: ["QQ", "大哭"] },
    { id: "qq-😰", name: "紧张", description: "紧张", path: cdn("😰", "png"), fallback: localPng("😰"), type: "image", tags: ["QQ", "紧张"] },
    { id: "qq-😱", name: "害怕", description: "害怕", path: cdn("😱", "png"), fallback: localPng("😱"), type: "image", tags: ["QQ", "害怕"] },
    { id: "qq-😳", name: "瞪眼", description: "瞪眼", path: cdn("😳", "png"), fallback: localPng("😳"), type: "image", tags: ["QQ", "瞪眼"] },
    { id: "qq-🙏", name: "合十", description: "合十", path: cdn("🙏", "png"), fallback: localPng("🙏"), type: "image", tags: ["QQ", "合十"] },
    { id: "qq-🚬", name: "吸烟", description: "吸烟", path: cdn("🚬", "png"), fallback: localPng("🚬"), type: "image", tags: ["QQ", "吸烟"] },
];

export const QQ_DEFAULT_STICKER_PACK: StickerPack = {
    id: "qq-default",
    name: "默认表情",
    icon: cdn("14", "apng"),
    iconType: "image",
    type: "image",
    density: "sm",
    description: "QQ 默认表情 · 小表情",
    stickers: QQ_DEFAULT_STICKERS,
};
